on: [push, pull_request]
name: Build
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        rust:
          - stable
          - beta
          - nightly
          - 1.80.0  # MSRV
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Build (no default features)
        run: cargo build --verbose --all --no-default-features
      - name: Build (log feature)
        run: cargo build --verbose --all --no-default-features --features=log
      - name: Build (log_parallelism feature)
        run: cargo build --verbose --all --no-default-features --features=log_parallelism
      - name: Build (rayon feature)
        run: cargo build --verbose --all --no-default-features --features=rayon
      - name: Build (default features)
        run: cargo build --verbose --all

      - name: Build (nightly feature)
        if: ${{ matrix.rust == 'nightly' }}
        run: cargo build --verbose --all --no-default-features --features=nightly
      - name: Build (nightly + log features)
        if: ${{ matrix.rust == 'nightly' }}
        run: cargo build --verbose --all --no-default-features --features=nightly,log
      - name: Build (nightly + log_parallelism features)
        if: ${{ matrix.rust == 'nightly' }}
        run: cargo build --verbose --all --no-default-features --features=nightly,log_parallelism
      - name: Build (nightly + rayon features)
        if: ${{ matrix.rust == 'nightly' }}
        run: cargo build --verbose --all --no-default-features --features=nightly,rayon
      - name: Build (nightly + default features)
        if: ${{ matrix.rust == 'nightly' }}
        run: cargo build --verbose --all --features=nightly
