on: [push, pull_request]
name: Build
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        rust:
          - stable
          - beta
          - nightly
          - 1.75.0  # MSRV
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Build (no default features)
        run: cargo build --verbose --all --no-default-features
      - name: Build (log feature)
        run: cargo build --verbose --all --no-default-features --features=log
      - name: Build (all features)
        run: cargo build --verbose --all --all-features
      - name: Build (default features)
        run: cargo build --verbose --all
