on: [push, pull_request]
name: Code coverage
jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-C debug_assertions"
      RUST_LOG: "debug"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage
        run: cargo llvm-cov --verbose --release --no-default-features --features log,log_parallelism,nightly_tests --workspace --lcov --output-path lcov.info
      - name: Generate code coverage with nightly APIs
        run: cargo llvm-cov --verbose --release --all-features --workspace --lcov --output-path lcov-nightly.info
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info,lcov-nightly.info
          verbose: true
          fail_ci_if_error: true
