on: [push, pull_request]
name: Build examples
jobs:
  build_examples:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        rust:
          - stable
          - beta
          - nightly
          - 1.81.0  # MSRV for examples
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Build examples (default features)
        run: cargo build --verbose --examples
