on: [push, pull_request]
name: Tests
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        rust:
          - stable
          - beta
          - nightly
          - 1.91.0  # MSRV for tests
        panic:
          - default
          - immediate-abort
        exclude:
          - rust: stable
            panic: immediate-abort
          - rust: beta
            panic: immediate-abort
          - rust: 1.91.0
            panic: immediate-abort
          - os: macos-latest
            panic: immediate-abort
          - os: windows-latest
            panic: immediate-abort
        include:
          - test_features: ""
          - all_test_features: ""
          - rust: nightly
            test_features: ",nightly,nightly_tests"
            all_test_features: "--features=nightly,nightly_tests"
          - panic: immediate-abort
            rustflags: "-Z unstable-options -C panic=immediate-abort -Z panic-abort-tests"
            cargoflags: "-Z build-std --target=x86_64-unknown-linux-gnu"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: "-D warnings -C debug_assertions ${{ matrix.rustflags }}"
      RUSTDOCFLAGS: "-D warnings -C debug_assertions ${{ matrix.rustflags }}"
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rust-src

      - name: Run tests (default features)
        run: cargo test ${{ matrix.cargoflags }} --release --verbose --all ${{ matrix.all_test_features }}
      - name: Run tests (log feature)
        run: cargo test ${{ matrix.cargoflags }} --release --verbose --all --features=log${{ matrix.test_features }}
      - name: Run tests (all features)
        run: cargo test ${{ matrix.cargoflags }} --release --verbose --all --features=log,log_parallelism,rayon${{ matrix.test_features }}
