on: [push, pull_request]
name: Tests with TSAN
jobs:
  tsan:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings -Zsanitizer=thread"
      RUSTDOCFLAGS: "-Zsanitizer=thread"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src

      - name: Run tests (no default features)
        run: cargo test --release -Zbuild-std --target=x86_64-unknown-linux-gnu --verbose --all --no-default-features --features=nightly,nightly_tests
      - name: Run tests (log feature)
        run: cargo test --release -Zbuild-std --target=x86_64-unknown-linux-gnu --verbose --all --no-default-features --features=log,nightly,nightly_tests
      - name: Run tests (log_parallelism feature)
        run: cargo test --release -Zbuild-std --target=x86_64-unknown-linux-gnu --verbose --all --no-default-features --features=log_parallelism,nightly,nightly_tests
